Merge conflicts opgelost en commentaar weggehaald.
Ik krijg af en toe wel de volgende foutmelding ivm de Toolbar. Deze wordt ergens niet goed gecast.:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: applab.veiligthuis, PID: 5031
    java.lang.ClassCastException: androidx.appcompat.widget.Toolbar$SavedState cannot be cast to android.widget.Toolbar$SavedState